apiVersion: v1
kind: PersistentVolume

metadata:
  name: my-website-pv

spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/my-website-data